name: Discord Notifier

on:
  pull_request_review:
    types: [submitted]

jobs:
  notify:
    
    if: contains(github.event.review.body, '!discord')
    runs-on: ubuntu-latest
    steps:
      - name: Send notification
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          content: "Nowa notka w PR! Autor: ${{ github.actor }}"
          title: "CR MACHEN"
          description: "${{ github.event.review.body }}"
          url: ${{ github.event.pull_request.html_url }}
          color: 0x00ff00
