name: Discord Notifier

on:
  issue_comment:
    types: [created]

jobs:
  notify:
    if: github.event.issue.pull_request && contains(github.event.comment.body, '!discord')
    runs-on: ubuntu-latest
    steps:
      - name: Send notification
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          content: "Nowa notka w PR! Autor: ${{ github.actor }}"
          title: "CR MACHEN"
          description: "${{ github.event.comment.body }}"
          url: ${{ github.event.issue.html_url }}
          color: 0x00ff00
